version: 2
jobs:
  test:
    working_directory: ~/rqlite/src/github.com/rqlite/gorqlite
    docker:
      - image: circleci/golang:1.12
      - image: rqlite/rqlite:7.6.1
    steps:
        - checkout
        - run: go vet .
        - run: go test -timeout 60s -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
